---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ${MOLECULE_DOCKER_IMAGE:-'geerlingguy/docker-ubuntu2004-ansible:latest'}
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: ansible
env:
  PY_COLORS: '1'
  ANSIBLE_FORCE_COLOR: '1'
