---
- name: Check whether packages are installed
  hosts: all
  become: yes

  tasks:

    - name: Verify utilities are available
      command: >
        {{ item }}
      with_items:
        - zint --help

